### ISSUE TITLE
Problems with addMissingValues

### ISSUE THREAD

**Issue by jsalinas69** [tomaztk/datasetR#1]
The statement 
my_dataset$ii_1 <- addMissingValues(my_dataset, ii_1, pc = 10)
returns the entire column with values missing NA

**Comment by tomaztk** [comment]
Thanks,  the wrong version of function addMissingValues was deployed. There is a line:` df_name[[col_name]]` missing at the end. Thanks for this precious test!

**Comment by tomaztk** [comment]
solved. 
install/download the new release and the correct function is available.

**Comment by jsalinas69** [comment]
Hi,

 

my_dataset$ii_2 <- addMissingValues(my_dataset, ii_1, pc = 10)

 

it gives me more than 10% of missing

 

When I test this statement

 

library(DataExplorer)

iris$Sepal.Length2 <- addMissingValues(iris, Sepal.Length, pc = 10)

plot_missing(iris)

 

it gives me more than 40% data lost

 

 

Thanks

 

 

De: Tomaz Kastrun ***@***.*** 
Enviado el: jueves, 13 de julio de 2023 11:14
Para: tomaztk/datasetR ***@***.***>
CC: jsalinas69 ***@***.***>; Author ***@***.***>
Asunto: Re: [tomaztk/datasetR] Problems with addMissingValues (Issue #1)

 

solved.
install/download the new release and the correct function is available.
