### ISSUE TITLE
Problems with addMissingValues()

### ISSUE THREAD

**Issue by jsalinas69** [tomaztk/datasetR#2]
Thanks, but when I test this statement

library(DataExplorer)
iris$Sepal.Length2 <- addMissingValues(iris, Sepal.Length, pc = 10)
plot_missing(iris)

it gives me more than 40% data lost

Thanks

**Comment by tomaztk** [comment]
Great find! With low dispersed data the percentage does not work, because it takes the values itself. I will rewrite the selected based on the positions of values in vector. I have done only a test on high volumes of data and high dispersity (spread).

**Comment by tomaztk** [comment]
Fixed. New release available.
